# Generated by Django 5.1.7 on 2025-04-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_produts_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('operating_sys', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=100)),
                ('memory', models.CharField(blank=True, max_length=100)),
                ('CPU', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('image', models.ImageField(default='', upload_to='uploads/product/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
