# Generated by Django 5.1.7 on 2025-04-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_products_brand_products_model_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='products',
            name='warranty',
        ),
        migrations.AddField(
            model_name='products',
            name='feature',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
    ]
