# Generated by Django 5.1.7 on 2025-04-10 05:21

from django.db import migrations

def convert_prices_forward(apps, schema_editor):
    Products = apps.get_model('store', 'Products')
    for product in Products.objects.all():
        if product.price is not None:
            product.price_inr = float(product.price) * 83  # 1 USD = 83 INR (approx)
            product.save()

def convert_prices_backward(apps, schema_editor):
    Products = apps.get_model('store', 'Products')
    for product in Products.objects.all():
        if product.price_inr is not None:
            product.price = float(product.price_inr) / 83  # Convert back to USD
            product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_products_price_inr_alter_products_price'),
    ]

    operations = [
        migrations.RunPython(convert_prices_forward, convert_prices_backward),
    ]
