"""
Django settings for ecom project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# Import necessary modules
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9@q96yk20*@gyo7&4&*t7o1w+d&wo8h3w-h)ynw^t%8v$)*)j_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# List of allowed hosts for the site; keep it empty in development
ALLOWED_HOSTS = []


# Application definition

# List of installed Django apps, including custom apps like 'store' and 'cart'
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom apps
    'store',
    'cart',
]

# Middleware settings to handle requests, security, sessions, etc.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Root URL configuration for the project
ROOT_URLCONF = 'ecom.urls'

# Template settings for rendering HTML templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # List of directories to search for templates
        'APP_DIRS': True,  # Enable app-level template directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',  # Context processor for cart details
            ],
        },
    },
]

# WSGI application used for deployment
WSGI_APPLICATION = 'ecom.wsgi.application'


# Database settings
# Using SQLite for simplicity; change to another database if needed
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Use SQLite database
        'NAME': BASE_DIR / 'db.sqlite3',  # Database file location
    }
}


# Password validation settings for user authentication
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Localization settings
LANGUAGE_CODE = 'en-us'  # Language for the application
TIME_ZONE = 'UTC'  # Time zone for the application

USE_I18N = True  # Enable internationalization
USE_TZ = True  # Enable time zone support


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'  # URL for serving static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')  # Additional directories for static files
]

MEDIA_URL = '/media/'  # URL for serving media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Directory for storing media files

# Default primary key field type for models
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Use BigAutoField for auto-incremented fields
